### ISSUE TITLE
多版本控制问题

### ISSUE THREAD

**Issue by wjyheropk** [QNJR-GROUP/EasyTransaction#1]
请问在补偿操作时，如果发现想要回滚的内容已经被另外的操作修改了，怎么办？

**Comment by skyesx** [comment]
这是一个业务问题，框架只负责补偿操作成功执行。

如果你想要通过补偿 回滚的内容 会由于被其他操作修改过而无法正确补偿的话，那么它就不是一个可补偿的业务场景。考虑调整业务以允许补偿，或者考虑调整成TCC

**Comment by wjyheropk** [comment]
除了查询以外，大多数涉及到增删改的操作都有这个问题吧
个人理解：除非服务端实现版本控制（补偿操作时，发现要回滚的内容已经被修改，那就报错，人工处理），否则补偿型事务是有问题的

**Comment by skyesx** [comment]
框架肯定是不知道，也没办法知道 你的业务记录有没有被修改。

然后，框架保证的是你的 补偿方法只被执行一遍，如果没有成功执行（抛出乐观锁等异常）那么框架会重试执行

所以当你的补偿业务程序遇到这些乐观锁之类的问题时，直接抛异常就可以了
