### ISSUE TITLE
com.yiqiniu.easytrans.executor.TccMethodExecutor 代码问题

### ISSUE THREAD

**Issue by qiankunli** [QNJR-GROUP/EasyTransaction#10]
![image](https://user-images.githubusercontent.com/8024725/28700555-0b8f031e-7383-11e7-9f5b-de81a5f3dc74.png)

当事务处理失败时，您创建了TccCallCancelledContent，但TccCallCancelledContent貌似应该用`logCtx.getLogCache().cacheLog(tccCallCanceledContent);`记录一下

**Comment by skyesx** [comment]
嗯嗯，确实应该需要调用这个，需要加上

不过这个没有记不影响程序最终的正确运行，可能导致的是在重复执行CrashRecover的时候，多调了这个补偿方法。但补偿方法是需要幂等的，所以没有影响。

**Comment by skyesx** [comment]
已修复
