### ISSUE TITLE
仅tcc模式，可以不用zk选举吗，zk选举是用在哪些模块了呢

### ISSUE THREAD

**Issue by JiangGuangxing** [QNJR-GROUP/EasyTransaction#117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**settings**
which type of idempotent support you use?(framework idempotent/business idempotent?)

which version and component do you use( redis/rdb log implement and redis/rdb version? kafka/ons queue implements and queue version? ribbon/dubbo rpc implements?)

**the relative records **
records in table executed_trans, idempotent, logs(trans_log_detail, trans_log_unfinished,or redis records)

**can you reproduce it in demos by changing certain settings**
this will help us understand the situation more effectively

**Additional context**

**Comment by skyesx** [comment]
* 用于在同一个ServiceId的服务实例内挑选出一个实例进行兜底补偿
* 用于存储字符串压缩的对应关系

通过自行修改这些实行，用Mysql、redis或者其他集中存储，可以替换掉ZK。

**Comment by skyesx** [comment]
已实现，请参考demo中的 nozk
