### ISSUE TITLE
能不能建交流群

### ISSUE THREAD

**Issue by nsspw** [QNJR-GROUP/EasyTransaction#12]
就Dubbo分布式事务这块，最好建个QQ交流群

**Comment by skyesx** [comment]
有问题优先ISSUE提把，方便知识沉淀

**Comment by skyvinXu** [comment]
还是希望大神建个群交流一下。哪怕我们关注者互相交流也方便。
另外，我是用的Spring Cloud 比较关心 feign rpc的进度。啥时候能用啊？
ps: 感谢大神提供的这个框架，统一解决事物问题. 非常受启发

**Comment by skyesx** [comment]
最后出来的可能不是FEIGN RPC而是仅仅是基于REST的接口及调用，不过SpringCloud一套肯定能直接用，应该12月份结束前能出来

群和ISSUE本质是一样的，还是优先提ISSUE把，你关心的问题或许也是别人关心的问题

**Comment by skyvinXu** [comment]
还没整出来么？等得花儿都谢了

**Comment by skyesx** [comment]
最近公司比较忙...12月前会出来的...

**Comment by skyvinXu** [comment]
2018.01.02

**Comment by skyesx** [comment]
已更新

**Comment by killkiss** [comment]
建立一个群吧！真的需要沟通

**Comment by skyesx** [comment]
各位有疑问的可以加我微信 skyesx，有问题我会尽量解答
