### ISSUE TITLE
Spring版本问题

### ISSUE THREAD

**Issue by jifengnan** [QNJR-GROUP/EasyTransaction#125]
看介绍，确实不错，但实际用得时候发现了个很棘手的问题。

这个框架好在和spring集成，但也坏在和spring集成。我们项目使用的spring cloud版本是F版，spring boot是2.x的，而ET使用的D版1.5.x的，这导致项目根本启动不起来。。。

**Comment by skyesx** [comment]
可以参考demo tccAndFescar 进行Maven依赖的调整，这里用的就是F版本

还有可以看Readme的第七段

**Comment by jifengnan** [comment]
惭愧
