### ISSUE TITLE
应用程序使用了aop，无法获取类上所标注的BusinessIdentifer注解。

### ISSUE THREAD

**Issue by dengchong1994** [QNJR-GROUP/EasyTransaction#128]
getRequestClass((Class<? extends BusinessProvider<?>>) provider.getClass());

**Comment by skyesx** [comment]
问题准确的来说是 Spring 代理了ET内部的BusinessProvider，一般来说，所有的其他外部切面增强都不应该在这里进行，若有增强必要，都应该加到业务的代码中。

要解决这个问题有几个方法：
* 去掉BusinessProvider的切面增强
* 或者使用 ET提供的注解声明形式替代BusinessProvider

在下一个版本将会增加兼容支持 经过代理的 BusinessProvider的处理
