### ISSUE TITLE
et还会继续维护吗？

### ISSUE THREAD

**Issue by klaus-pd** [QNJR-GROUP/EasyTransaction#129]
作者还有继续升级维护的计划吗，似乎很久没有更新了，fascar已经到了0.7版本，有同步升级计划吗

**Comment by skyesx** [comment]
会继续维护，seata版本也会更新上去，近期会有较大一个版本

**Comment by dargoner** [comment]
> 会继续维护，seata版本也会更新上去，近期会有较大一个版本

9月份会发布上来吗

**Comment by skyesx** [comment]
国庆期间会发上来

**Comment by skyesx** [comment]
已更新Seata版本
