### ISSUE TITLE
多数据源问题咨询

### ISSUE THREAD

**Issue by ji123vj** [QNJR-GROUP/EasyTransaction#27]
你好，看了你写的测试用例，有几个问题想咨询下。业务库新建了executed_trans和idempotent分别做事务状态记录和幂等记录。整个测试用例订单服务、积分、账户都使用同一个数据库。服务请求方和服务提供方都需要更新或者记录这两张表。如果现在有需求把订单服务分离出来，订单数据也需要独立出来，那么你这个框架是不是就不支持了？

**Comment by skyesx** [comment]
支持的。分离出来的库都有这两张表就可以了

**Comment by skyesx** [comment]
不需要共同维护，事务状态只由发起方维护（级联事务里由父事务维护），幂等状态只由被调用方（从事务）维护

**Comment by ji123vj** [comment]
好的，我先学习下。有问题在咨询你。非常感谢。
