### ISSUE TITLE
求提供mockservice涉及到表的表结构

### ISSUE THREAD

**Issue by SandyJiang** [QNJR-GROUP/EasyTransaction#3]
想在dubbo调用多个provider场景实现补偿，不会用。然后发现mockserver也不知道怎么跑。求支持。

**Comment by skyesx** [comment]
MockService表结构会通过方法 com.yiqiniu.easytrans.test.FullTest.cleanAndSetUp() 自动创建

要快速跑起来的话，将readme.md里面的表结构都创建到同一个库里，配置好server.properties里面的相关参数（test.jdbc.url就直接填刚刚创建的库），包括 JDBC,ZK,以及阿里云的ONS

然后执行测试方法 com.yiqiniu.easytrans.test.FullTest.test()，里面会调用MockService，以及测试各种异常场景

**Comment by SandyJiang** [comment]
我们这种穷屌丝公司用不起ons。用的别的mq，而且我个人想用在dubbo上，都需要排掉ons的哪些配置啊。

**Comment by skyesx** [comment]
额......ONS确实不具有通用型，后续计划提供个ActiveMq的扩展

要跑起来的话，ONS的配置不用排除也不用配置，只是跑UT时通过队列完成的业务数据会不对，UT结果错误而已。

你可以裁剪 com.yiqiniu.easytrans.test.mockservice.order.OrderService.buySomething(int, long) 这个方法里面调用的远程方法，并对这个方法进行编写对应的UT，测试你想要测试的场景

**Comment by SandyJiang** [comment]
建议搞成可配的，因为mq天生自带最大努力实现。我们的异步的业务，用rabbitmq搞的，从来没重过、丢过数据。所以在mq场景可能不考虑事物问题。

**Comment by skyesx** [comment]
嗯，好的，确实有关掉MQ的需求

**Comment by skyesx** [comment]
关闭MQ的实现已有，请参考tcc-only这个demo。
