### ISSUE TITLE
咨询下是否支持Sharing-JDBC

### ISSUE THREAD

**Issue by soedev** [QNJR-GROUP/EasyTransaction#30]
数据库分库分表，框架是否支持，如果支持的话，有什么需要特殊配置吗

**Comment by skyesx** [comment]
支持

但每个分库下都要有框架对应的表，所以SJ也要配置 EasyTransaction 的路由规则

**Comment by skyesx** [comment]
关于SJ类的分片框架，个人有篇文章，供参考 http://www.infoq.com/cn/articles/new-idea-of-rdb-fragmentation/

**Comment by soedev** [comment]
谢谢，在咨询下使用rpc-rest-ribbon，自定义HttpHeaders参数是否可以传递，用于多租户的身份识别，动态切换数据源

**Comment by skyesx** [comment]
这个之前没有考虑到，能否详细描述下需求 是否发送端只要有途径能加上 header即可？接收端有啥需求？

我把对应的功能做上去或者给出解决方案

**Comment by skyesx** [comment]
最好提新ISSUE描述新问题

**Comment by soedev** [comment]
发送端加上header可以添加自定义内容即可，接收端有什么拦截器可以前置处理下
