### ISSUE TITLE
关于服务提供方事务的问题

### ISSUE THREAD

**Issue by ji123vj** [QNJR-GROUP/EasyTransaction#33]
服务提供方对外接口是在RestRibbonEasyTransRpcProviderImpl中指定的，返回通过反射执行具体业务实现。这块的事务是怎么保障的？

**Comment by skyesx** [comment]
事务的保障跟 RestRibbonEasyTransRpcProviderImpl 这个没有很大关系。

保障事务的是  补偿、最终一致、TCC、幂等 这些手段。
如果一定要找联系的话，就是在RestRibbonEasyTransRpcProviderImpl的代码使得在调用业务代码前，加入了 上述的一些手段，从而保障最终一致性

**Comment by ji123vj** [comment]
那我可以理解为，经过了这个代码RestRibbonEasyTransRpcProviderImpl，到达业务代码以后自身带事务吗？如果，业务层操作了一系列的表以后，抛了异常，数据会回滚！我实际测试是回滚的，但是没有看到开启事务的代码（即没有看到cglib的代理层），请问这一块是怎么实现的。

**Comment by ji123vj** [comment]
好的，谢谢！！
