### ISSUE TITLE
能不能把阿里的 ons换成其他开源的消息队列啊？？

### ISSUE THREAD

**Issue by youbooks** [QNJR-GROUP/EasyTransaction#4]
首先感谢您的无私分享，这个框架你那边能不能把阿里ONS换成其他的MQ啊，例如ActiveMq

**Comment by skyesx** [comment]
正在进行中，这一两周会有更新

**Comment by youbooks** [comment]
好的，幸苦了

**Comment by simon518** [comment]
有没有文档呢？没有注释的源代码看着好费劲

**Comment by skyesx** [comment]
目前没有，我尽量加

**Comment by simon518** [comment]
除了测试代码，源代码能不能也加一些注释呢？

**Comment by skyesx** [comment]
不好意思呀，最近比较忙，说之前要搞一个新的MQ，但最后没有搞，后续可能会添加ActiveMq的支持了，可能基于Spring Cloud Stream来接入Mq，这个东西可以屏蔽底层具体的MQ目前支持 RabbitMq和Kafka

调研完后会开始开发

**Comment by ExtremeYu** [comment]
@skyesx 请问你们最后打算用spirng cloud stream 了吗？spring cloud bus 似乎也也可以？

**Comment by skyesx** [comment]
公司没有用spring cloud stream,Spring cloud Stream是为了方便大家扩展使用计划加上的

spring cloud bus在我看来只是在 spring cloud stream基础上构建的，为Spring cloud整合一些特殊功能（如 配置变更广播）的一个组件，所以不会依赖于Spring cloud bus构建
