### ISSUE TITLE
tcc和compensable的本质区别

### ISSUE THREAD

**Issue by ji123vj** [QNJR-GROUP/EasyTransaction#41]
你好，这两种类型的请求的本质却别是什么？是2PC和3PC的区别吗？适用场景有啥不同？谢谢。

**Comment by skyesx** [comment]
compensable流程上看成阉割版本的tcc,但他们应对的场景不同。使用TCC也能模仿compensable的行为，只是消耗比较大，也违背了设计初衷。

compensable的操作理念是 子事务直接完成修改，若主事务提交了，那么就不再做任何操作。但主事务回滚了，则执行一个操作，撤销之前的操作。

tcc的操作理念则是预留资源，主事务提交了，则预留的资源真正扣除，若回滚了，则资源预留取消。

compensable适用于资源可做反向操作的，如我扣了钱，可以给你补回去。但是我给你加了钱，用户就可能直接用掉了，我们就扣不走了，这就不适合compensable，这个可以用数据队列来加钱，或者使用tcc。

**Comment by ji123vj** [comment]
利用可靠消息或者不可靠消息来做的话，是否需要有序队列？还是要看具体的业务逻辑了？

**Comment by skyesx** [comment]
看业务。但一般来说最好不需要有序队列。一旦依赖于有序，有一个消息消费失败则后续都不能消费
