### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by githubzy** [QNJR-GROUP/EasyTransaction#59]
hi 
does it have quick start
thank u

**Comment by skyesx** [comment]
there's a quick start demo here, but it's only in tcc model, i will add more start demo recently:
https://github.com/QNJR-GROUP/EasyTransaction/tree/master/easytrans-demo/tcc-only

but you can find more usage in unit test:
https://github.com/QNJR-GROUP/EasyTransaction/blob/master/easytrans-starter/src/test/java/com/yiqiniu/easytrans/test/FullTest.java

**Comment by githubzy** [comment]
thanks
