### ISSUE TITLE
导入框架，所需的注意的点（步骤、配置、导入包等），可否说明

### ISSUE THREAD

**Issue by mponeto** [QNJR-GROUP/EasyTransaction#6]
看说明，使用很简单，但是导入不知道怎么入手

**Comment by narci2010** [comment]
项目要运行起来的确不容易啊。

**Comment by skyesx** [comment]
接下来的功能开发会暂停，优先做DEMO和文档

**Comment by xiaominger** [comment]
在父项目根目录mvn clean install 的时候怎么报错？The project com.yiqiniu.easytrans:easytrans-starter:[unknown-version] (---/EasyTransaction/easytrans-starter/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.yiqiniu.easytrans:easytrans-starter:[unknown-version]: Failure to find com.yiqiniu.easytrans:easytrans:pom:1.0.0-SNAPSHOT

**Comment by skyesx** [comment]
项目已增加demo,请参考。
