### ISSUE TITLE
建议每次更新的时候改一下版本号

### ISSUE THREAD

**Issue by renyiran** [QNJR-GROUP/EasyTransaction#79]
你好 建议每次更新的时候改一下版本号吧 特别是传到中央仓库的话 如果修改包但是版本号没变就很蛋疼~

**Comment by skyesx** [comment]
嗯，在中央仓库的的版本号肯定会递增的，之前还没有加到中央仓库，所以版本一直没有变

每次发布到中央仓库前统一改一次版本
