### ISSUE TITLE
TCC demo 远程调用堵塞

### ISSUE THREAD

**Issue by laziobird** [QNJR-GROUP/EasyTransaction#86]
https://github.com/QNJR-GROUP/EasyTransaction/tree/1.x/easytrans-demo 
Demo 似乎work不了，OrderService ，WalletService 可以正常起来，但是OrderService 127.0.0.1:8080/buySth?userId=1&money=15 远程调用WalletService，一直请求堵塞，不知道原因

**Comment by skyesx** [comment]
具体哪个demo?有什么报错日志？

**Comment by laziobird** [comment]
两个demo都是，tcc-only , rpc-dubbo.服务都正常启动，没报错，只是zookeeper 提示 Got user-level KeeperException   Error:KeeperErrorCode = NodeExists

**Comment by laziobird** [comment]
断点调试，执行到 
OrderService		
transaction.startEasyTrans(BUSINESS_CODE, id);
堵塞
如果注释掉这段，远程调用		
		Future<WalletPayResponseVO> deductFuture = transaction.execute(deductRequest);
堵塞

**Comment by skyesx** [comment]
卡住了多久？一直不停？后续有没有报错？ZK和数据库有没有配置正确？

如果检查了ZK和数据库的配置都正确的话，你把完整的两个应用的日志和配置传上来看下？


我的微信可以在关注公众号后看到

**Comment by laziobird** [comment]
嗯，很感谢skyesx 的指导，查明原因 部署环境zookeeper 版本过低，
ZooKeeper Compatibility
Apache Curator is meant to be used with ZooKeeper 3.5+. However, it is also compatible with ZooKeeper 3.4.x. See Compatibility for details.
我升级ZK到3.4以后就可以了
