### ISSUE TITLE
希望作者能多提供一种基于注解的配置来降低业务程序的耦合度

### ISSUE THREAD

**Issue by lsq890410** [QNJR-GROUP/EasyTransaction#88]
现在ET提供的两种写法已经能满足业务需求，但是在配置上和传统的注解方式不太一致。希望作者能提供基于注解的RPC调用方式。这样方便不同的框架自主选择。统一业务框架的代码编写方式

**Comment by skyesx** [comment]
已于1.2.x版本提供，可参考interface这个demo
