### ISSUE TITLE
是否对已有代码侵入较大

### ISSUE THREAD

**Issue by qiankunli** [QNJR-GROUP/EasyTransaction#9]
对于已有的项目
1. 调用方几乎重写
2. 被调用方要实现接口
是否可以使用aspectj，通过注解的形式，来减少对现有代码的影响呢？

**Comment by skyesx** [comment]
谢谢建议，确实通过注解的形式来实现会减少入侵，实现也不会很复杂

下一个发布的版本我一起加上吧，不过我也不知道下一次是啥时候，或者欢迎你提个PR~

**Comment by qiankunli** [comment]
方便给个联系方式么，我最近一阵也在处理分布式事务方面的问题

**Comment by skyesx** [comment]
更正，使用注解形式，对于提供方实现不难
但对于调用方，目前是强制需要提供 全局事务ID，以及返回结果前置变成了FUTURE
改动还是有点多....

有问题直接提ISSUE吧，方便知识沉淀

**Comment by qiankunli** [comment]
方便联系，好多向您请教一些东西
