### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: org.apache.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lorg/apache/curator/framework/api/ProtectACLCreateModePathAndBytesable;

### ISSUE THREAD

**Issue by lnnnogithub** [QNJR-GROUP/EasyTransaction#92]
Caused by: java.lang.NoSuchMethodError: org.apache.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lorg/apache/curator/framework/api/ProtectACLCreateModePathAndBytesable;

**Comment by skyesx** [comment]
具体描述下场景？

**Comment by yuluyi** [comment]
碰到了同样的问题。 
场景就是启动的时候，curator报了这个错。 debugger的inspector里creatingParentsIfNeeded这个方法能被调用而且正常返回，但是代码执行的时候，就报NoSuchMethodError

**Comment by yuluyi** [comment]
解决了， 我用的gradle
不知道为什么 下过来的1.1.3的jar的pom里，curator-recipes 依赖是2.2.1
而实际下载的curator-recipes 和curator-framework都是4.0.1

```gradle
compile('com.yiqiniu.easytrans:easytrans-starter:1.1.3') {
        exclude module: 'easytrans-queue-kafka-starter'
        exclude module: 'curator-recipes'
    }
    
    compile('org.apache.curator:curator-recipes:2.11.1') {
        exclude module: 'curator-framework'
    }

    compile('org.apache.curator:curator-framework:2.11.1')
```
暂时这样解决了

**Comment by lnnnogithub** [comment]
> @skyesx
> 解决了， 我用的gradle
> 不知道为什么 下过来的1.1.3的jar的pom里，curator-recipes 依赖是2.2.1
> 而实际下载的curator-recipes 和curator-framework都是4.0.1
> 
> ```groovy-gradle
> compile('com.yiqiniu.easytrans:easytrans-starter:1.1.3') {
>         exclude module: 'easytrans-queue-kafka-starter'
>         exclude module: 'curator-recipes'
>     }
>     
>     compile('org.apache.curator:curator-recipes:2.11.1') {
>         exclude module: 'curator-framework'
>     }
> 
>     compile('org.apache.curator:curator-framework:2.11.1')
> ```
> 
> 暂时这样解决了

不好意思，最近没看github

**Comment by dmh920** [comment]
我的没有解决，springboot2.x，curator改成2.11.1后，还是出现这个问题

**Comment by lnnnogithub** [comment]
> 我的没有解决，springboot2.x，curator改成2.11.1后，还是出现这个问题

要不我PR这段代码吧^_^，造福大家

**Comment by skyesx** [comment]
欢迎PR

**Comment by skyesx** [comment]
具体请参考已更新的readme    七、外部组件版本兼容性
